### ISSUE TITLE
ENHANCEMENT: Documentation clarification & request for install help

### ISSUE THREAD

**Issue by bcurran3** [netvolt/LinuxRMM-Script#38]
(new install of Tactical RMMv1.2.0 today)

Requesting some updating/clarification to the documentation.

> 1. Mesh agent
> 
>   The url given by mesh for installing new agent.
>   Go to mesh.example.com > Add agent > Installation Executable Linux / BSD / macOS > **Select the good system type**
>   Copy **ONLY** the URL with the quote.

Following the above instructions I don't have an option to Add Agent at mesh.example.com. I can get a list of agents at mesh.example.com/meshagents though. I know where the option should be as it's a choice in my separate MeshCentral setup. Maybe this has changed in a newer version of TRMM since the docs were written.

> 6. Agent Type
> 
>   Can be *server* or *workstation* and define the type of agent.
>   
> ### Example
> ```bash
> ./rmmagent-linux.sh install 'https://mesh.example.com/meshagents?id=XXXXX&installflags=X&meshinstall=X' 'https://api.example.com' 3 1 'XXXXX' server
> ```

The "id=XXXXX&installflags=X&meshinstall=X" string has really confused me.  Should both the XXXXX and two locations of X be replaced with the meshagent ID? If yes, it would be more intuitive to have "id=X&installflags=X&meshinstall=X" as the XXXXX and two positions of X appear to be different variables. IMHO it would be more clear to put something along the lines of "id=[meshclientid]&installflags=[meshclientid]&meshinstall=[meshclientid]" and maybe a note not to include the brackets.

Now if I'm wrong on how the "id=XXXXX&installflags=X&meshinstall=X" part is supposed to be modified, and I'm guessing I am, could someone please explain the XXXX variable and the two instances of the X variable?

In my case I can get the agent to install using just "id=6" and using "id=6&installflags=6&meshinstall=6" but in both instances when I go to TRMM/Remote Background, TERMINAL and FILE BROWSER don't work yet PROCESSES works in some cases.  (DISCLAIMER: I've installed both ways on a DietPi v9.14.2 install and an Ubuntu 22.04.5 LTS install. PROCESSES has worked and not worked and I forget which OS and which install parameters I used to get which results.)

Using MeshCentral I can get a remote terminal to my Linux boxes (DietPi and multiple flavors of Ubuntu). Using TRMM and the meshagent I can't. I'm not sure if it's a client install issue or a TRMM limitation or something else. Anyone have any insight for me? (I'd really like to not have to keep a discrete instance of MeshCentral running just for Linux support!)

**Comment by bcurran3** [comment]
Looking at my mesh.example.com, I noticed that the Linux server is not showing in My Devices.

**This seems to be the root problem:** The Agent is connecting to the Tactical RMM dashboard but NOT connecting to TRMM's mesh/MeshCentral integration. This makes sense as the TERMINAL and FILE BROWSER functions of Remote Background are functions in MeshCentral while the (working) PROCESSES function is not part of MeshCentral.

So I uninstalled and re-installed about three times with no luck.

Here's the install output after Go is installed:

> Go is installed.
> --2025-07-02 13:02:02--  https://trmmmesh.example.com/meshagents?id=20
> Resolving trmmmesh.example.com (trmmmesh.example.com)... 192.168.69.206
> Connecting to trmmmesh.example.com (trmmmesh.example.com)|192.168.69.206|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 3454384 (3.3M) [application/octet-stream]
> Saving to: ‘/tmp/meshagent’
> 
> /tmp/meshagent                100%[=================================================>]   3.29M  --.-KB/s    in 0.02s
> 
> 2025-07-02 13:02:02 (166 MB/s) - ‘/tmp/meshagent’ saved [3454384/3454384]
> 
> ...Checking for previous installation of "meshagent" [NONE]
> ...Installing service [DONE]
>    -> Starting service... [OK]
> rm: cannot remove '/tmp/meshagent.msh': No such file or directory
> Agent Compile begin
> --2025-07-02 13:02:09--  https://github.com/amidaware/rmmagent/archive/refs/heads/master.tar.gz
> Resolving github.com (github.com)... 140.82.116.3
> Connecting to github.com (github.com)|140.82.116.3|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://codeload.github.com/amidaware/rmmagent/tar.gz/refs/heads/master [following]
> --2025-07-02 13:02:09--  https://codeload.github.com/amidaware/rmmagent/tar.gz/refs/heads/master
> Resolving codeload.github.com (codeload.github.com)... 140.82.116.9
> Connecting to codeload.github.com (codeload.github.com)|140.82.116.9|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: unspecified [application/x-gzip]
> Saving to: ‘/tmp/rmmagent.tar.gz’
> 
> /tmp/rmmagent.tar.gz              [ <=>                                              ]  70.38K  --.-KB/s    in 0.06s
> 
> 2025-07-02 13:02:10 (1.06 MB/s) - ‘/tmp/rmmagent.tar.gz’ saved [72065]
> 
> INFO[0000] Adding agent to dashboard
> WARNING: Unable to read board_asset_tag: open /sys/class/dmi/id/board_asset_tag: no such file or directory
> WARNING: Unable to read board_serial: open /sys/class/dmi/id/board_serial: no such file or directory
> WARNING: Unable to read board_vendor: open /sys/class/dmi/id/board_vendor: no such file or directory
> WARNING: Unable to read board_version: open /sys/class/dmi/id/board_version: no such file or directory
> WARNING: Unable to read board_name: open /sys/class/dmi/id/board_name: no such file or directory
> INFO[0007] Installation was successful!
> Allow a few minutes for the agent to properly display in the RMM
> Created symlink /etc/systemd/system/multi-user.target.wants/tacticalagent.service → /etc/systemd/system/tacticalagent.service.
> Tactical Agent Install is done

(Ignore the end warnings, my setup is a Proxmox VM that evidently doesn't include that hw info.)

my install command:

> sudo ./rmmagent-linux.sh install 'https://trmmmesh.example.com/meshagents?id=20' 'https://trmmapi.example.com' 1 1 'redacted' server

**Comment by Brandon-Roff** [comment]
Good Day,

``` bash /tmp/meshagent 100%[=================================================>] 3.29M --.-KB/s in 0.02s

2025-07-02 13:02:02 (166 MB/s) - ‘/tmp/meshagent’ saved [3454384/3454384]

...Checking for previous installation of "meshagent" [NONE]
...Installing service [DONE]
-> Starting service... [OK]
rm: cannot remove '/tmp/meshagent.msh': No such file or directory
```

This is normally an issue with the install Flag, now your mesh URL does not look right at all it should look lke

```
https://mesh.example.com/meshagents?id=[KEY]&installflags=0&meshinstall=6
```

As you're using Proxmox, your machines will be 64-bit, which is why the agent for tactical RMM is being installed. If you don't choose the right Architecture in Mesh Central, it won't install the mesh agent properly, i had the same issue when installing a Raspberry Pi. 

meshinstall=6 - Seems to be the ARCH 64 tag. I plan to automate this in the script (currently in testing phase) so it will use the correct mesh tag by architecture 

Arm6/7(armhf)= meshinstall=25
AMD64 = meshinstall=6
ARM64 = meshinstall=26


Also, if you're not seeing add device option, ensure you're logged into the original details for Mesh Central created at your install, then you will see this option.


In regards to your message about the X Values in Documentation, the mesh ID is normally 15+ characters, the install flagis  1 digit, and the mesh install max 2, same for activation token.

Hope that Helps!

**Comment by Brandon-Roff** [comment]
The Command needs to be full so the correct architeture of GO can complile the correct agent

**Comment by bcurran3** [comment]
@Brandon-Roff 

Thanks for the help. Unfortunately I'm still stuck. What you said makes sense, but I still don't understand where the id=XXXXX/id=[KEY] comes from or any formatting around the key.

I did go to my mesh server and downloaded a meshaction.txt. In it fields for remoteNodeId, serverId, and serverHttpsHash. Which one should it be.

"Intuitively" I ran with the value in serverId and attempted to install without any single or double quotes or square brackets. Checking my mesh server, the Linux box didn't appear in the list. I attempted again with single quotes around the value and another couple variations until I had to remove 5 or more agents for the same box from the TRMM main UI.

I'm sure I attempted too many times and need to reboot to get it installed correctly because I'm getting an error:

> cp: cannot create regular file '/usr/local/bin/rmmagent': Text file busy
> INFO[0000] Adding agent to dashboard
> 2025/08/07 21:54:16 createAgentConfig Config File "/etc/tacticalagent" Already Exists

I assume if I reboot it will install correctly when I have the parameters correct (or possibly manually remove all the install files - The PS script does that automatically, I haven't didn't check the bash script and too lazy to do right now as I'm pressed for time.)

Am I correct in assuming that mesh server ID is the serverId value? And if so, should I encapsulate it in anything or just through it in between the id= and &install?

Thanks in advance!

**Comment by Brandon-Roff** [comment]
I have pushed my changes to my side

https://github.com/Brandon-Roff/LinuxRMM-Script

**Comment by bcurran3** [comment]
@Brandon-Roff 

Sorry, I'm not trying to be rude, but none of that helps.

I have tried your script, but I still have a new different problem. I will move the discussion there. You're in-tune and active on this and I do appreciate it.

**Comment by Brandon-Roff** [comment]
@bcurran3 Not a Problem maybe i miss understand your issue, ill see you on my thread

**Comment by Brandon-Roff** [comment]
@bcurran3  Let me open issues (sorry) then move this there ok

**Comment by netvolt** [comment]
Hello @bcurran3, 

I dont think that should use "/meshagents?id=6" at your command line. 
Since new version, dont need to go to get Mesh code anymore. We need to update it at instructions. 

Try this (get the Windows **Manual** auth code):

./rmmagent-linux.sh install 'https://mesh.example.com' 'https://api.example.com' 1' 27 'auth_code_from_tactical_RMM' server

Regards

**Comment by Brandon-Roff** [comment]
@netvolt, we have solved his issue on my fork as he is using the new changes i have made

Regards
